In [2]:
import pickle
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import os
from scipy.stats import linregress

In [3]:
#read in the data frame
with open('df.pickle','rb') as read_file:
    df = pickle.load(read_file)

In [4]:
# show the first twenty rows of the data frame
df.head(20)

,gender,age,scholarship,hypertension,diabetes,alcoholism,handicap,sms,no_show,schedule_hour,schedule_day,appointment_day,day_difference,appointment_weekday,schedule_weekday,prior_appointments,prior_noshows,total_conditions
2149,1.0,40,0.0,0.0,0.0,0.0,0.0,1.0,1.0,10,29,29,31.0,5.0,2.0,0,0.0,0.0
2154,1.0,25,0.0,0.0,0.0,0.0,0.0,1.0,1.0,16,29,29,31.0,5.0,2.0,0,0.0,0.0
2155,1.0,49,0.0,0.0,0.0,0.0,0.0,0.0,0.0,17,28,29,1.0,5.0,4.0,0,0.0,0.0
2158,1.0,58,0.0,0.0,0.0,0.0,0.0,1.0,0.0,10,29,29,31.0,5.0,2.0,0,0.0,0.0
2161,0.0,23,0.0,0.0,0.0,0.0,0.0,1.0,0.0,10,29,29,31.0,5.0,2.0,0,0.0,0.0
2162,0.0,41,0.0,0.0,0.0,0.0,0.0,0.0,0.0,15,29,29,0.0,5.0,5.0,0,0.0,0.0
2167,1.0,33,0.0,0.0,0.0,0.0,0.0,0.0,0.0,10,29,29,0.0,5.0,5.0,0,0.0,0.0
2148,0.0,32,0.0,0.0,0.0,0.0,0.0,1.0,1.0,11,29,29,31.0,5.0,2.0,0,0.0,0.0
2170,1.0,26,0.0,0.0,0.0,0.0,0.0,0.0,0.0,8,15,29,14.0,5.0,5.0,0,0.0,0.0
2127,0.0,47,0.0,0.0,0.0,0.0,0.0,0.0,0.0,9,29,29,0.0,5.0,5.0,0,0.0,0.0
2132,1.0,14,0.0,0.0,0.0,0.0,0.0,0.0,0.0,8,7,29,22.0,5.0,4.0,0,0.0,0.0
2134,1.0,13,0.0,0.0,0.0,0.0,0.0,1.0,0.0,13,6,29,23.0,5.0,3.0,0,0.0,0.0
2137,0.0,37,0.0,0.0,0.0,0.0,0.0,0.0,1.0,13,6,29,23.0,5.0,3.0,0,0.0,0.0
2146,1.0,79,0.0,1.0,0.0,0.0,0.0,0.0,0.0,13,18,29,11.0,5.0,1.0,0,0.0,1.0
2200,0.0,30,0.0,0.0,0.0,0.0,0.0,0.0,0.0,9,29,29,0.0,5.0,5.0,0,0.0,0.0
2202,1.0,53,1.0,1.0,0.0,0.0,0.0,1.0,0.0,9,1,29,59.0,5.0,2.0,0,0.0,1.0
2204,1.0,36,0.0,0.0,0.0,0.0,0.0,0.0,0.0,9,1,29,59.0,5.0,2.0,0,0.0,0.0
2210,0.0,45,0.0,0.0,0.0,0.0,0.0,0.0,0.0,11,29,29,0.0,5.0,5.0,0,0.0,0.0
2215,0.0,12,1.0,0.0,0.0,0.0,0.0,0.0,0.0,14,29,29,0.0,5.0,5.0,0,0.0,0.0
2217,0.0,48,0.0,0.0,0.0,0.0,0.0,0.0,0.0,11,28,29,1.0,5.0,4.0,0,0.0,0.0

In [5]:
target = df["hypertension"]
target_names = ["negative", "positive"]

In [6]:
data = df.drop("hypertension", axis=1)
feature_names = data.columns
data.head()

,gender,age,scholarship,diabetes,alcoholism,handicap,sms,no_show,schedule_hour,schedule_day,appointment_day,day_difference,appointment_weekday,schedule_weekday,prior_appointments,prior_noshows,total_conditions
2149,1.0,40,0.0,0.0,0.0,0.0,1.0,1.0,10,29,29,31.0,5.0,2.0,0,0.0,0.0
2154,1.0,25,0.0,0.0,0.0,0.0,1.0,1.0,16,29,29,31.0,5.0,2.0,0,0.0,0.0
2155,1.0,49,0.0,0.0,0.0,0.0,0.0,0.0,17,28,29,1.0,5.0,4.0,0,0.0,0.0
2158,1.0,58,0.0,0.0,0.0,0.0,1.0,0.0,10,29,29,31.0,5.0,2.0,0,0.0,0.0
2161,0.0,23,0.0,0.0,0.0,0.0,1.0,0.0,10,29,29,31.0,5.0,2.0,0,0.0,0.0

In [7]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(data, target, random_state=42)

In [8]:
# Support vector machine linear classifier
from sklearn.svm import SVC

model = SVC(kernel='linear')
model.fit(X_train, y_train)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
    kernel='linear', max_iter=-1, probability=False, random_state=None,
    shrinking=True, tol=0.001, verbose=False)

In [9]:
# Model Accuracy
print('Test Acc: %.3f' % model.score(X_test, y_test))

Test Acc: 1.000

In [10]:
# Calculate classification report
from sklearn.metrics import classification_report

predictions = model.predict(X_test)
print(classification_report(y_test, predictions,
                            target_names=target_names))

              precision    recall  f1-score   support

    negative       1.00      1.00      1.00     12533
    positive       1.00      1.00      1.00      3036

    accuracy                           1.00     15569
   macro avg       1.00      1.00      1.00     15569
weighted avg       1.00      1.00      1.00     15569